// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Country struct {
	Code      int    `json:"code"`
	Name      string `json:"name"`
	Continent string `json:"continent"`
}

type Merchant struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	AdminID     string `json:"adminID"`
	CountryCode int    `json:"countryCode"`
	CreateTime  string `json:"createTime"`
}

type Order struct {
	ID         string `json:"id"`
	UserID     string `json:"userID"`
	Status     string `json:"status"`
	CreateTime string `json:"createTime"`
}

type Product struct {
	ID         string `json:"id"`
	MerchantID string `json:"merchantID"`
	Name       string `json:"name"`
	Price      int    `json:"price"`
	Status     string `json:"status"`
	CreateTime string `json:"createTime"`
}

type User struct {
	ID          string `json:"id"`
	FName       string `json:"FName"`
	Email       string `json:"email"`
	Gender      string `json:"gender"`
	DoB         string `json:"DoB"`
	CountryCode int    `json:"countryCode"`
	CreateTime  string `json:"createTime"`
}

type UserCreate struct {
	UserID    *string `json:"userID"`
	UserFName string  `json:"userFName"`
	UserLName string  `json:"userLName"`
}
